config/routes.rb
Rails.application.routes.draw do



  resources :links

  resources :courses do
    resources :posts do
      resources :comments
    end
  end
  resources :posts do
    collection {post :import}
  end
  resources :comments do
    collection {post :import}
  end
  resources :app_settings

  devise_for :users, controllers: { registrations: 'user_registrations/registrations'}

  resources :grid_images, only: [:create, :new, :destroy]

  resources :template_ones do
    resources :projects
    resources :grid_image_categories, only: [:create, :new, :destroy]
    resources :pages
  end



 
  resources :incoming_contacts

  root to: 'template_ones#show'
  get 'edit_about', to: 'template_ones#edit_about'
  get 'edit_services', to: 'template_ones#edit_services'
  get 'edit_process', to: 'template_ones#edit_process' 
  get 'edit_header', to: 'template_ones#edit_header' 
  get 'edit_contact', to: 'template_ones#edit_contact' 
  get 'edit_action', to: 'template_ones#edit_action' 
  get 'edit_testimonial', to: 'template_ones#edit_testimonial' 
  get 'edit_portfolio_carousel', to: 'template_ones#edit_portfolio_carousel'
  get 'edit_portfolio_carousel_heading', to: 'template_ones#edit_portfolio_carousel_heading'
  get 'edit_portfolio_grid', to: 'template_ones#edit_portfolio_grid'
  get 'edit_footer', to: 'template_ones#edit_footer'
  get 'edit_navigation', to: 'template_ones#edit_navigation'
  get 'edit_newsletter', to: 'template_ones#edit_newsletter'


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/app_setting.rb
class AppSetting < ApplicationRecord


 validates_presence_of :tab_name, :theme_name


  private

  NAVBAR_COLOR = %w(
    primary
    light
    dark
  )

  FRONT_END_COLOR = %w(
    aqua
    blue
    green
    orange
    pink
    purple
    red
    tan
    turquoise
    yellow
  )

  APP_THEME = %w(  
    default
    cerulean
    darkly
    litera
    materia
    sandstone
    slate
    superhero
    cosmo
    flatly
    lumen
    minty
    simplex
    solar
    united
    cyborg
    journal
    lux
    pulse
    sketchy
    spacelab
    yeti
  )
end

app/controllers/app_settings_controller.rb
class AppSettingsController < ApplicationController
  before_action :set_app_setting, only: [:show, :edit, :update, :destroy]
  before_action :admin_user
  before_action :authenticate_user!

  # GET /app_settings
  # GET /app_settings.json
  def index
    @app_settings = AppSetting.all
  end

  # GET /app_settings/1
  # GET /app_settings/1.json
  def show
  end

  # GET /app_settings/new
  def new
    @app_setting = AppSetting.new
  end

  # GET /app_settings/1/edit
  def edit
  end

  # POST /app_settings
  # POST /app_settings.json
  def create
    @app_setting = AppSetting.new(app_setting_params)

    respond_to do |format|
      if @app_setting.save
        format.html { redirect_to @app_setting, notice: 'App setting was successfully created.' }
        format.json { render :show, status: :created, location: @app_setting }
      else
        format.html { render :new }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_settings/1
  # PATCH/PUT /app_settings/1.json
  def update
    respond_to do |format|
      if @app_setting.update(app_setting_params)
        format.html { redirect_to @app_setting, notice: 'App setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_setting }
      else
        format.html { render :edit }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_settings/1
  # DELETE /app_settings/1.json
  def destroy
    @app_setting.destroy
    respond_to do |format|
      format.html { redirect_to app_settings_url, notice: 'App setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private

    def admin_user
      if !current_user.try(:admin) == true 
        flash[:danger] = "The resource does not exist"
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_app_setting
      @app_setting = AppSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_setting_params
      params.require(:app_setting).permit(:tab_name, :theme_name, :front_end_color, :app_title, :app_email_1, :app_email_2, :app_email_title_1, :app_email_title_2, :navbar_color)
    end
end

app/helpers/app_settings_helper.rb
module AppSettingsHelper
end

app/views/app_settings/_form.html.erb
<%= simple_form_for(@app_setting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tab_name %>
    <%= f.input :theme_name, collection: AppSetting::APP_THEME, include_blank: false %> 
    <%= f.input :navbar_color, collection: AppSetting::NAVBAR_COLOR, include_blank: false %>
    <%= f.input :front_end_color, collection: AppSetting::FRONT_END_COLOR, include_blank: false %>
    <%= f.input :app_title %>
    <%= f.input :app_email_title_1 %>
    <%= f.input :app_email_1 %> 
    <%= f.input :app_email_title_2 %> 
    <%= f.input :app_email_2 %>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/app_settings/edit.html.erb
<h1>Editing App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Show', @app_setting %> |
<%= link_to 'Back', app_settings_path %>

app/views/app_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Settings</h1>

<table>
  <thead>
    <tr>
      <th>Tab name</th>
      <th>Theme name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_settings.each do |app_setting| %>
      <tr>
        <td><%= app_setting.tab_name %></td>
        <td><%= app_setting.theme_name %></td>
        <td><%= link_to 'Show', app_setting %></td>
        <td><%= link_to 'Edit', edit_app_setting_path(app_setting) %></td>
        <td><%= link_to 'Destroy', app_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Setting', new_app_setting_path %>

app/views/app_settings/new.html.erb
<h1>New App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Back', app_settings_path %>

app/views/app_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tab name:</strong>
  <%= @app_setting.tab_name %>
</p>

<p>
  <strong>Theme name:</strong>
  <%= @app_setting.theme_name %>
</p>

<%= link_to 'Edit', edit_app_setting_path(@app_setting) %> |
<%= link_to 'Back', app_settings_path %>