config/routes.rb
Rails.application.routes.draw do



  resources :links

  resources :courses do
    resources :posts do
      resources :comments
    end
  end
  resources :posts do
    collection {post :import}
  end
  resources :comments do
    collection {post :import}
  end
  resources :app_settings

  devise_for :users, controllers: { registrations: 'user_registrations/registrations'}

  resources :grid_images, only: [:create, :new, :destroy]

  resources :template_ones do
    resources :projects
    resources :grid_image_categories, only: [:create, :new, :destroy]
    resources :pages
  end



 
  resources :incoming_contacts

  root to: 'template_ones#show'
  get 'edit_about', to: 'template_ones#edit_about'
  get 'edit_services', to: 'template_ones#edit_services'
  get 'edit_process', to: 'template_ones#edit_process' 
  get 'edit_header', to: 'template_ones#edit_header' 
  get 'edit_contact', to: 'template_ones#edit_contact' 
  get 'edit_action', to: 'template_ones#edit_action' 
  get 'edit_testimonial', to: 'template_ones#edit_testimonial' 
  get 'edit_portfolio_carousel', to: 'template_ones#edit_portfolio_carousel'
  get 'edit_portfolio_carousel_heading', to: 'template_ones#edit_portfolio_carousel_heading'
  get 'edit_portfolio_grid', to: 'template_ones#edit_portfolio_grid'
  get 'edit_footer', to: 'template_ones#edit_footer'
  get 'edit_navigation', to: 'template_ones#edit_navigation'
  get 'edit_newsletter', to: 'template_ones#edit_newsletter'


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :template_one 

  mount_uploader :image_1, ProjectImageUploader
  mount_uploader :image_2, ProjectImageUploader
  mount_uploader :modal_image_1, ProjectImageUploader
  mount_uploader :modal_image_2, ProjectImageUploader
  mount_uploader :modal_image_3, ProjectImageUploader
  mount_uploader :modal_image_4, ProjectImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :find_the_template, except: [:index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = @template_one.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_portfolio_carousel_path(@template_one), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        flash[:danger] = @project.errors.full_messages.to_sentence
        format.html { redirect_to edit_portfolio_carousel_path }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to edit_portfolio_carousel_path(@template_one), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        flash[:danger] = @project.errors.full_messages.to_sentence
        format.html { redirect_to edit_portfolio_carousel_path }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to edit_portfolio_carousel_path(@template_one), notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def find_the_template
      @template_one = TemplateOne.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
      :name, 
      :description, 
      :button_text, 
      :image_1, 
      :image_2, 
      :template_one_id,
      :modal_name,
      :modal_description,
      :modal_client,
      :modal_date,
      :modal_service,
      :modal_image_1,
      :modal_image_2,
      :modal_image_3,
      :modal_image_4
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for [@template_one, @project] do |f| %> 
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :button_text %>
    <label>Main Image</label>
    <%= f.input :image_1, as: :file, label: false %> 
    <label>Side Image</label>
    <%= f.input :image_2, as: :file, label: false %>
    <%= f.input :template_one_id %>
<h3>Modal Section</h3>
    <%= f.input :modal_name %>
    <%= f.input :modal_description %>
    <%= f.input :modal_client %>
    <%= f.input :modal_date %>
    <%= f.input :modal_service %>
      <label>Modal Main</label>
    <%= f.input :modal_image_1, as: :file, label: false %>
      <label>Modal Item 1</label>
    <%= f.input :modal_image_2, as: :file, label: false %>
      <label>Modal Item 2</label>
    <%= f.input :modal_image_3, as: :file, label: false %>
      <label>Modal Item 3</label>
    <%= f.input :modal_image_4, as: :file, label: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>


<%= link_to 'Back', edit_portfolio_carousel_path(@template_one), class: 'btn btn-success' %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Button text</th>
      <th>Image 1</th>
      <th>Image 2</th>
      <th>Template one</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.button_text %></td>
        <td><%= project.image_1 %></td>
        <td><%= project.image_2 %></td>
        <td><%= project.template_one_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', edit_portfolio_carousel_path(@template_one), class: 'btn btn-success' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Button text:</strong>
  <%= @project.button_text %>
</p>

<p>
  <strong>Image 1:</strong>
  <%= @project.image_1 %>
</p>

<p>
  <strong>Image 2:</strong>
  <%= @project.image_2 %>
</p>

<p>
  <strong>Template one:</strong>
  <%= @project.template_one_id %>
</p>
<%= link_to 'Back', edit_portfolio_carousel_path(@template_one), class: 'btn btn-success' %>