config/routes.rb
Rails.application.routes.draw do



  resources :links

  resources :courses do
    resources :posts do
      resources :comments
    end
  end
  resources :posts do
    collection {post :import}
  end
  resources :comments do
    collection {post :import}
  end
  resources :app_settings

  devise_for :users, controllers: { registrations: 'user_registrations/registrations'}

  resources :grid_images, only: [:create, :new, :destroy]

  resources :template_ones do
    resources :projects
    resources :grid_image_categories, only: [:create, :new, :destroy]
    resources :pages
  end



 
  resources :incoming_contacts

  root to: 'template_ones#show'
  get 'edit_about', to: 'template_ones#edit_about'
  get 'edit_services', to: 'template_ones#edit_services'
  get 'edit_process', to: 'template_ones#edit_process' 
  get 'edit_header', to: 'template_ones#edit_header' 
  get 'edit_contact', to: 'template_ones#edit_contact' 
  get 'edit_action', to: 'template_ones#edit_action' 
  get 'edit_testimonial', to: 'template_ones#edit_testimonial' 
  get 'edit_portfolio_carousel', to: 'template_ones#edit_portfolio_carousel'
  get 'edit_portfolio_carousel_heading', to: 'template_ones#edit_portfolio_carousel_heading'
  get 'edit_portfolio_grid', to: 'template_ones#edit_portfolio_grid'
  get 'edit_footer', to: 'template_ones#edit_footer'
  get 'edit_navigation', to: 'template_ones#edit_navigation'
  get 'edit_newsletter', to: 'template_ones#edit_newsletter'


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/controllers/template_ones_controller.rb
class TemplateOnesController < ApplicationController
  before_action :set_template_one, only: [:show, :edit, :update, :destroy, :edit_about, :edit_services, :edit_process, :edit_header, :edit_contact, :edit_action, :edit_testimonial, :edit_portfolio_carousel, :edit_portfolio_carousel_heading, :edit_portfolio_grid, :edit_footer, :edit_navigation, :edit_newsletter] 
  before_action :authenticate_user!, except: [:show]
  
  before_action :not_admin_user, only: [:edit, :update, :destroy, :index, :edit_about, :edit_services, :edit_process, :edit_header, :edit_contact, :edit_action, :edit_testimonial, :edit_portfolio_carousel, :edit_portfolio_carousel_heading, :edit_portfolio_grid, :edit_footer, :edit_navigation, :edit_newsletter]
  layout 'template_ones' 
  # GET /template_ones
  # GET /template_ones.json
  def index
    flash[:danger] = "Not a valid path." 
    redirect_back(fallback_location: root_path)
    @template_ones = TemplateOne.all
  end

  # GET /template_ones/1
  # GET /template_ones/1.json
  def show
    # if current_user and not current_user.try(:admin?)
    # if current_user && !current_user.try(:admin?)
    #   redirect_to course_posts_path 
    # end
    @projects = Project.all
    @incoming_contact = IncomingContact.new 
    @posts = Post.last(@template_one.testimonial_count).reverse  
    @grid_image_categories = GridImageCategory.all
    @grid_images = GridImage.all
    @links = Link.all
    @pages = @template_one.pages
  end

  # GET /template_ones/new
  def new
    @template_one = TemplateOne.new
  end

  # GET /template_ones/1/edit
  def edit
  end

  # POST /template_ones
  # POST /template_ones.json
  def create
    @template_one = TemplateOne.new(template_one_params)

    respond_to do |format|
      if @template_one.save
        format.html { redirect_to @template_one, notice: 'Template one was successfully created.' }
        format.json { render :show, status: :created, location: @template_one }
      else
        format.html { render :new }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_ones/1
  # PATCH/PUT /template_ones/1.json
  def update
    respond_to do |format|
      if @template_one.update(template_one_params)
        format.html { redirect_back fallback_location: root_path, notice: 'Template one was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_one }
      else
        flash[:danger] = "There was a problem! " + @template_one.errors.full_messages.to_sentence
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_ones/1
  # DELETE /template_ones/1.json
  def destroy
    @template_one.destroy
    respond_to do |format|
      format.html { redirect_to template_ones_url, notice: 'Template one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_about
  end

  def edit_services
  end

  def edit_process
  end

  def edit_header
  end

  def edit_contact
    @incoming_contact = IncomingContact.new 
  end

  def edit_action 
  end
 
  def edit_testimonial 
    @posts = Post.last(@template_one.testimonial_count).reverse
  end

  def edit_portfolio_carousel
    @projects = Project.all
  end

  def edit_portfolio_carousel_heading
  end

  def edit_portfolio_grid
    @grid_image_category = GridImageCategory.new
    @grid_image_categories = GridImageCategory.all
    @grid_image = GridImage.new
    @grid_images = GridImage.all
  end

  def edit_footer
  end

  def edit_navigation
  end

  def edit_newsletter
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template_one
      @template_one = TemplateOne.find(1)
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def template_one_params
      params.require(:template_one).permit(
        :about_image_show_default,
        :about_hide, 
        :about_title,
        :about_text,
        :about_text_2,
        :about_image,
        :service_hide,
        :service_icon_1,
        :service_title_1,
        :service_text_1,
        :service_icon_2,
        :service_title_2,
        :service_text_2,
        :service_icon_3,
        :service_title_3,
        :service_text_3,
        :service_icon_4,
        :service_title_4,
        :service_text_4,
        :service_title_5,
        :service_text_5,
        :process_hide, 
        :main_process_title,
        :main_process_title_text,
        :process_icon_1,
        :sub_title_1,
        :process_li_1,
        :process_li_2,
        :process_li_3,
        :process_li_4,
        :process_icon_2,
        :sub_title_2,
        :process_li_5,
        :process_li_6,
        :process_li_7,
        :process_li_8,
        :process_icon_3,
        :sub_title_3,
        :process_li_9,
        :process_li_10,
        :process_li_11,
        :process_li_12,
        :header_hide,
        :header_title, 
        :header_text,
        :header_image,
        :contact_hide,
        :contact_title,
        :contact_text,
        :contact_sender_hide_name,  
        :contact_sender_name,
        :contact_sender_hide_email,
        :contact_sender_email,
        :contact_sender_hide_phone,
        :contact_sender_phone,
        :contact_sender_hide_message,
        :contact_sender_message,
        
        :email_address_1, 
        :email_address_2, 
        :email_address_3, 
        :header_svg,
        :header_use_default_svg,
        :header_use_default_image,

        :action_hide,
        :action_text_1,
        :action_text_2,
        :action_text_3,
        :action_text_4,
        :action_text_5,
        :action_text_6,   
        :action_text_7,
        :action_button_text,
        :action_use_default_image,
        :action_image, 
        :testimonial_hide,
        :testimonial_count,
        :portfolio_carousel_hide,
        :portfolio_header_hide,
        :portfolio_header_title,
        :portfolio_header_text,
        :portfolio_grid_hide,
        :portfolio_grid_title,
        :portfolio_grid_text,
        :footer_hide,
        :footer_hide_telephone,
        :footer_icon_telephone,
        :footer_telephone_title,
        :footer_telephone_number,
        :footer_hide_address,
        :footer_icon_address,
        :footer_address_title,
        :footer_address_street,
        :footer_address_city,
        :footer_address_state,
        :footer_address_postal_code,
        :footer_hide_email,
        :footer_icon_email,
        :footer_email_title,
        :footer_email_address,
        :footer_hide_social_1, 
        :footer_social_icon_1,
        :footer_social_url_1,
        :footer_hide_social_2,
        :footer_social_icon_2,
        :footer_social_url_2,
        :footer_hide_social_3,
        :footer_social_icon_3,
        :footer_social_url_3,
        :footer_hide_social_4,
        :footer_social_icon_4,
        :footer_social_url_4,
        :footer_hide_social_5,
        :footer_social_icon_5,
        :footer_social_url_5,
        :footer_hide_social_6,
        :footer_social_icon_6,
        :footer_social_url_6,
        :footer_use_default_image,
        :footer_image,
        :navigation_hide,
        :navigation_title,
        :newsletter_hide,
        :newsletter_title

        )
    end
end

app/helpers/template_ones_helper.rb
module TemplateOnesHelper
end

app/views/template_ones/partials/_action.html.erb
   <!-- Call to Action -->
   <% if @template_one.action_hide == false %>
   <% if @template_one.action_use_default_image == true || !@template_one.action_image_url.present?   %>
    <section class="call-to-action" id="action" style="background-image: url(<%= asset_url 'template_ones/creative/backgrounds/bg-quote.jpg'%>);">
    <% else %>
    <section class="call-to-action" style="background-image: url(<%= asset_url @template_one.action_image_url(:version_1900x1267) if @template_one.action_image_url.present? %>);">
    <% end %>
      <div class="container wow fadeIn">
        <div class="row">
          <div class="col-md-10 mx-auto">
            <span class="quote">
                <%= @template_one.action_text_1 %>
              <span class="text-primary">
                <%= @template_one.action_text_2 %>
              </span>
                <%= @template_one.action_text_3 %>
              <span class="text-primary">
                <%= @template_one.action_text_4 %>
              </span>
                <%= @template_one.action_text_5 %>
              <span class="text-primary">
                <%= @template_one.action_text_6 %>
              </span>
                <%= @template_one.action_text_7 %>
              </span>
            <hr class="colored">
            <a class="btn btn-primary js-scroll-trigger" href="#contact">
              <%= @template_one.action_button_text %>
            </a>
          </div>
        </div>
      </div>
    </section>
    <% end %>
<%= link_to "Edit Action", edit_action_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %> 

app/views/template_ones/partials/_action_button.html.erb
    <!-- Block Button Call to Action -->
    <a class="btn btn-block btn-full-width" href="https://wrapbootstrap.com/theme/vitality-multipurpose-one-page-theme-WB02K3KK3">Buy Vitality Now!</a>

app/views/template_ones/partials/_contact.html.erb
<% if @template_one.contact_hide == false %>
<!-- Contact Section -->
<section class="page-section" id="contact">
  <div class="container wow fadeIn">
    <div class="text-center">
      <h2><%= @template_one.contact_title %></h2>
      <hr class="colored">
      <p><%= @template_one.contact_text %></p>
    </div>
    <div class="row mt-4">
      <div class="col-lg-8 mx-auto">
        <%= simple_form_for @incoming_contact do |ic| %>
        <form name="sentMessage" id="contactForm" novalidate>
        <% if @template_one.contact_sender_hide_name == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Name</label>
              <%= ic.input :name, label: false, placeholder: "Name" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Email Address</label>
              <%= ic.input :email, label: false, placeholder: "Email" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% if @template_one.contact_sender_hide_phone == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <%= ic.input :phone, label: false, placeholder: "Telephone" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <% if @template_one.contact_sender_hide_message == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Message</label>
              <%= ic.input :message, label: false, placeholder: "Message" %> 
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <br>
          <div id="success"></div>
          <div class="row">
            <div class="form-group col-12">
              <%= ic.submit "Send Message", class: 'btn btn-info' %>   
            </div>
          </div>
        </form>
        <% end %>
      </div>
    </div>
  </div>
</section>
<% end %>
<%= link_to "Edit Contact", edit_contact_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %>

app/views/template_ones/partials/_contact_1.html.erb
<% if @template_one.contact_hide == false %>
<!-- Contact Section -->
<section class="page-section" id="contact">
  <div class="container wow fadeIn">
    <div class="text-center">
      <h2>Need Reputation Management Assistance?</h2>
      <hr class="colored">
      <p><%= @template_one.contact_text %></p>
    </div>
    <div class="row mt-4">
      <div class="col-lg-8 mx-auto">
        <%= simple_form_for @incoming_contact do |ic| %>
        <form name="sentMessage" id="contactForm" novalidate>
        <% if @template_one.contact_sender_hide_name == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Name</label>
              <%= ic.input :name, label: false, placeholder: "Name" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Email Address</label>
              <%= ic.input :email, label: false, placeholder: "Email" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% if @template_one.contact_sender_hide_phone == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <%= ic.input :phone, label: false, placeholder: "Telephone" %>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <% if @template_one.contact_sender_hide_message == false %>
          <div class="row control-group">
            <div class="form-group col-12 floating-label-form-group controls">
              <label>Message</label>
              <%= ic.input :message, label: false, placeholder: "Message" %> 
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <% end %>
          <br>
          <div id="success"></div>
          <div class="row">
            <div class="form-group col-12">
              <%= ic.submit "Send Message", class: 'btn btn-info' %>   
            </div>
          </div>
        </form>
        <% end %>
      </div>
    </div>
  </div>
</section>
<% end %>
<%= link_to "Edit Contact", edit_contact_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %>

app/views/template_ones/partials/_footer.html.erb
<% if @template_one.footer_hide == false %>
<!-- Footer -->
<% if @template_one.footer_use_default_image? ||   
  !@template_one.footer_image.present? %>
<footer class="footer" style="background-image: url(<%= asset_url 'template_ones/footer.png' %>)">
<% else %>
<footer class="footer" style="background-image: url(<%= asset_url @template_one.footer_image_url(:footer) if @template_one.footer_image.present? %>)">
  <% end %>  
  <div class="container text-center">
    <div class="row">
      <div class="col-md-4 footer-contact-details">
        <% if @template_one.footer_hide_telephone == false %>
        <h4>
          <i class="fa fa-<%= @template_one.footer_icon_telephone %>"></i>
          <%= @template_one.footer_telephone_title %>
        </h4>
        <p><%= @template_one.footer_telephone_number %></p>
        <% end %>
      </div>
      <div class="col-md-4 footer-contact-details">
        <% if @template_one.footer_hide_address == false %>
        <h4>
          <i class="fa fa-<%= @template_one.footer_icon_address %>"></i>
          <%= @template_one.footer_address_title %>
        </h4>
        <p><%= @template_one.footer_address_street %><br>
          <%= @template_one.footer_address_city %>
          <%= @template_one.footer_address_state %> 
          <%= @template_one.footer_address_postal_code %>
        </p>
        <% end %>
      </div>
      <div class="col-md-4 footer-contact-details">
        <% if @template_one.footer_hide_email == false %>
        <h4>
          <i class="fa fa-<%= @template_one.footer_icon_email %>"></i>
          <%= @template_one.footer_email_title %>
        </h4>
        <p>
          <%= mail_to @template_one.footer_email_address %>
        </p>
        <% end %>
      </div>
    </div>
    <div class="row footer-social">
      <div class="col-lg-12">
        <ul class="list-inline">
          <% if @template_one.footer_hide_social_1 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_1, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_1 %> fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
          <% if @template_one.footer_hide_social_2 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_2, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_2 %>  fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
          <% if @template_one.footer_hide_social_3 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_3, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_3 %>  fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
          <% if @template_one.footer_hide_social_4 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_4, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_4 %>  fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
          <% if @template_one.footer_hide_social_5 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_5, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_5 %>  fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
          <% if @template_one.footer_hide_social_6 == false %>
          <li class="list-inline-item">
            <%= link_to "http://" + @template_one.footer_social_url_6, target: :_blank do %>
            <i class="fa fa-<%= @template_one.footer_social_icon_6 %>  fa-fw fa-2x"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div> 
    <p class="copyright">&copy; <%= Time.now.strftime('%Y') %> <%= @app_setting.app_title %></p>
  </div>
</footer>
<% end %>
<%= link_to "Edit Footer", edit_footer_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %> 

app/views/template_ones/partials/_navigation_1.html.erb
<!-- Navigation -->
<% if !@template_one.navigation_hide? %>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav"> 
  <div class="container">

  <%= link_to root_path, class: 'navbar-brand' do %>

    <%= image_tag 'ciLogo100.png', class: 'logo' %>
    <%= @template_one.navigation_title %> 
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa fa-bars"></i>
    Menu
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <% if !@pages.nil? %> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Resources <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
          <% @pages.each do |page| %>
          <% if !page.hide? && page.show_in_dropdown? %>
             <%= link_to page.title, template_one_page_path(@template_one, page), class: 'dropdown-item' %>
          <% end %>
          <% end %>
          </div>
        </li>
        <% end %>
 

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Apps <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
            <% @links.each do |link| %>
            <% if link.open_in_new_tab? %>
            <%= link_to "http://#{link.url}", target: '_blank', class: "dropdown-item" do %>
            <%= link.name %>
            <% end %>
            <% else %>
            <%= link_to "http://#{link.url}", class: "dropdown-item" do %>
            <%= link.name  %>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </li>
        <% if current_user.try(:admin?) %> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Admin <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
            <%= link_to "Backend", courses_path, class: 'dropdown-item' %>  
            <%= link_to "Administration", rails_admin_path, class: 'dropdown-item', target: :_blank %>  
            <%= link_to 'text', new_template_one_page_path(@template_one), class: 'dropdown-item' %>
            <%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %> 
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>  
          </div>
        </li>
        <% end %>
        <% if !current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Account <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
            <%= link_to "Sign In", new_user_session_path, class: 'dropdown-item' %>  
            <div class="dropdown-divider"></div>
            <%= link_to "Create Account", new_user_registration_path, class: 'dropdown-item' %> 
          </div>
        </li>
        <% elsif current_user && current_user.try(:admin) == false %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download"><%= current_user.first_name %> <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
            <%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %> 
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>  
          </div>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Select Course <span class="caret"></span></a>
          <div class="dropdown-menu" aria-labelledby="download">
            <% Course.all.each do |course| %>
            <%= link_to course.name, course_path(course), class: 'dropdown-item' %>
            <% end %>
          </div>
        </li>
        <% if current_user.try(:admin?) %>  
        <li class="nav-item">
          <%= link_to "Edit Navigation", edit_navigation_path, class: "btn btn-outline-info btn-sm" %> 
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/template_ones/partials/_newsletter.html.erb
<% if @template_one.newsletter_hide == false %>
    <!-- Newsletter Signup Call to Action -->
    <section class="page-section signup-form bg-inverse text-white">
      <div class="container text-center">
        <h3 class="m0"><%= @template_one.newsletter_title %></h3>
        <hr class="colored">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <!-- MailChimp Signup Form -->
            <div id="mc_embed_signup">
              <!-- Replace the form action in the line below with your MailChimp embed action! Visit the documentation for additional instructions! -->
              <form role="form" action="//startbootstrap.us3.list-manage.com/subscribe/post?u=531af730d8629808bd96cf489&amp;id=afb284632f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
                <div class="input-group input-group-lg">
                  <input type="email" name="EMAIL" class="form-control" id="mce-EMAIL" placeholder="Email address...">
                  <span class="input-group-btn">
                    <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">Subscribe!</button>
                  </span>
                </div>
                <div id="mce-responses">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>
              </form>
            </div>
            <!-- End MailChimp Signup Form -->
          </div>
        </div>
      </div>
    </section>
<% end %>
<%= link_to "Edit Newsletter", edit_newsletter_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %> 

app/views/template_ones/partials/_portfolio_carousel.html.erb
<% if @template_one.portfolio_carousel_hide != true %>
<!-- Portfolio Carousel -->
<div class="portfolio-carousel wow fadeIn owl-carousel owl-theme">
  <!-- Portfolio Carousel Item 4 -->
  <% @projects.each do |project| %>
  <div class="item" style="background-image: url(<%= asset_url project.image_1_url(:image_1) if project.image_1.present? %>)">
    <div class="container-fluid">
      <div class="row h-100">
        <div class="col-md-7 my-auto d-none d-sm-block">
          <div class="device-container">
            <div class="device-mockup macbook portrait black">
              <div class="device">
                <div class="screen">
                  <img class="img-fluid" src="<%= asset_url project.image_2_url(:image_2) if project.image_2.present? %>" alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-5 my-auto">
          <div class="project-details">
            <span class="project-name"><%= project.name %></span>
            <span class="project-description"><%= project.description %></span>
            <hr class="colored">
            <a href="#portfolioModal1" data-toggle="modal" class="btn btn-primary"><%= project.button_text %>
            <i class="fa fa-long-arrow-right fa-fw"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>
<%= link_to "Edit Portfolio Carousel", edit_portfolio_carousel_path, class: "btn btn-outline-info btn-sm pull-right" if current_user.try(:admin?) %> 

<%= link_to "Edit Portfolio Heading", edit_portfolio_carousel_heading_path, class: "btn btn-outline-info btn-sm pull-left" if current_user.try(:admin?) %> 

app/views/template_ones/partials/_portfolio_carousel_heading.html.erb
<% if @template_one.portfolio_header_hide == false %> 
<!-- Portfolio Carousel Heading -->
<section class="page-section bg-light" id="work">
  <div class="container text-center wow fadeIn">
    <h2><%= @template_one.portfolio_header_title %></h2>
    <hr class="colored">
    <p><%= @template_one.portfolio_header_text %></p>
  </div>
</section>        
<% end %>