config/routes.rb
Rails.application.routes.draw do



  resources :links

  resources :courses do
    resources :posts do
      resources :comments
    end
  end
  resources :posts do
    collection {post :import}
  end
  resources :comments do
    collection {post :import}
  end
  resources :app_settings

  devise_for :users, controllers: { registrations: 'user_registrations/registrations'}

  resources :grid_images, only: [:create, :new, :destroy]

  resources :template_ones do
    resources :projects
    resources :grid_image_categories, only: [:create, :new, :destroy]
    resources :pages
  end



 
  resources :incoming_contacts

  root to: 'template_ones#show'
  get 'edit_about', to: 'template_ones#edit_about'
  get 'edit_services', to: 'template_ones#edit_services'
  get 'edit_process', to: 'template_ones#edit_process' 
  get 'edit_header', to: 'template_ones#edit_header' 
  get 'edit_contact', to: 'template_ones#edit_contact' 
  get 'edit_action', to: 'template_ones#edit_action' 
  get 'edit_testimonial', to: 'template_ones#edit_testimonial' 
  get 'edit_portfolio_carousel', to: 'template_ones#edit_portfolio_carousel'
  get 'edit_portfolio_carousel_heading', to: 'template_ones#edit_portfolio_carousel_heading'
  get 'edit_portfolio_grid', to: 'template_ones#edit_portfolio_grid'
  get 'edit_footer', to: 'template_ones#edit_footer'
  get 'edit_navigation', to: 'template_ones#edit_navigation'
  get 'edit_newsletter', to: 'template_ones#edit_newsletter'


  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
end

app/models/post.rb
class Post < ApplicationRecord


  validates :title, length: { minimum: 4, maximum: 150 } 
  # validates :body, length: { minimum: 1 }
  belongs_to :user
  belongs_to :course
  has_many :comments, dependent: :destroy 
  validates_inclusion_of :lecture_number, in: 1..5000, message: "Value must a number > 0"
  # validates_inclusion_of :section_number, in: 1..5000, message: "Value must a number > 0"


RUBY_SECTIONS = [
["Section 1 - The Set Up", "Section 1 - The Set Up"], 
["Section 2 - Some Of The Basics", "Section 2 - Some Of The Basics"],
['Section 3 - Variables', 'Section 3 - Variables'],
['Section 4 - Welcome to Git', 'Section 4 - Welcome to Git'],
['Section 5 - It\'s a String Thing', 'Section 5 - It\'s a String Thing'],
['Section 6 - Ruby Loves Arithmetic', 'Section 6 - Ruby Loves Arithmetic'],
['Section 7 - Ruby Methods', 'Section 7 - Ruby Methods'],
['Section 8 - Ruby Operators', 'Section 8 - Ruby Operators'],
['Section 9 - Getting Input and Interaction', 'Section 9 - Getting Input and Interaction'],
['Section 10 - Arrays', 'Section 10 - Arrays'],
['Section 11 - The Hash', 'Section 11 - The Hash'],
['Section 12 - Mission Impossible', 'Section 12 - Mission Impossible'],
['Section 13 - Conditions and Loops', 'Section 13 - Conditions and Loops'],
['Section 14 - Ruby Has Class', 'Section 14 - Ruby Has Class'],
['Section 15 - Working With Files', 'Section 15 - Working With Files'],
['Section 16 - Errors', 'Section 16 - Errors'],
['Section 17 - Search WIth Grep', 'Section 17 - Search WIth Grep'],
['Section 18 - Gems', 'Section 18 - Gems'],
['Section 19 - Build A Gem', 'Section 19 - Build A Gem'],
['Section 20 - Ruby Gaming', 'Section 20 - Ruby Gaming'],
['Section 21 - Galigoo', 'Section 21 - Galigoo'],
['Rails', 'Rails'],


['Section 1 - Welcome', 'Section 1 - Welcome'],
['Section 2 - The Set Up', 'Section 2 - The Set Up'],
['Section 3 - Overview', 'Section 3 - Overview'],
['Section 4 - Rails CRUD (create, read, update, destroy)', 'Section 4 - Rails CRUD (create, read, update, destroy)'],
['Section 5 - Generators', 'Section 5 - Generators'],
['Section 6 - Gems and Forms', 'Section 6 - Gems and Forms'],

['Section 7 - An App With Users', 'Section 7 - An App With Users'],
['Section 8 - Users With Custom Fields', 'Section 8 - Users With Custom Fields'],
['Section 9 - Posts With Comments', 'Section 9 - Posts With Comments'],
['Section 10 - Recover Password', 'Section 10 - Recover Password'],
['Section 11 - Send Comment Emails', 'Section 11 - Send Comment Emails'],
['Section 12 - Seeding Data', 'Section 12 - Seeding Data'],
['Section 13 - Run It In The Background', 'Section 13 - Run It In The Background'],
['Section 14 - User Image', 'Section 14 - User Image'],
['Section 15 - Free Templating', 'Section 15 - Free Templating'],
['Section 16 - Potpourri', 'Section 16 - Potpourri'],
['Section 17 - Front End', 'Section 17 - Front End'],
['Section 18 - Administration', 'Section 18 - Administration'],
['Section 19 - User Authorization', 'Section 19 - User Authorization'],
['Section 20 - User Access', 'Section 20 - User Access'],
['Section 21 - Theme Image', 'Section 21 - Theme Image'],
['Section 22 - Content Management', 'Section 22 - Content Management'],
['Section 23 - Project', 'Section 23 - Project'],
['Section 24 - Action', 'Section 24 - Action'],
['Section 25 - Header', 'Section 25 - Header'],
['Section 26 - Footer', 'Section 26 - Footer'],
['Section 27 - Order & Time', 'Section 27 - Order & Time'],
['Section 28 - Template Authorization', 'Section 28 - Template Authorization'],
['Section 29 - Deploy', 'Section 29 - Deploy'],
['Section 30 - Receive Mail', 'Section 30 - Receive Mail'],
['Section 31 - Admin Navi', 'Section 31 - Admin Navi'],
['Section 32 - Post On Home', 'Section 32 - Post On Home'],
['Section 33 - Portfolio Grid Prep', 'Section 33 - Portfolio Grid Prep'],
['Section 34 - Portfolio Grid', 'Section 34 - Portfolio Grid'],
['Section 35 - Potpourri Two', 'Section 35 - Potpourri Two'],
['Section 36 - Colors and Custom', 'Section 36 - Colors and Custom'],
['Section 37 - More Validation', 'Section 37 - More Validation'],
['Section 38 - Deploy Part Two', 'Section 38 - Deploy Part Two'],
['Section 39 - JQuery', 'Section 39 - JQuery'],
['Section 40 - Heroku Deploy', 'Section 40 - Heroku Deploy'],
['Section 41 - Potpourri Three', 'Section 41 - Potpourri Three'],
['Section 42 - Course Resources', 'Section 42 - Course Resources']
]

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)	
    CSV.foreach(file.path, headers: true) do |row|
      Post.create! row.to_hash     
    end
  end  


end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :not_owner_of_post, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!

  
  def index
    not_administrator
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @course = Course.find(params[:course_id]) 
  end

  # GET /posts/new
  def new
    not_administrator
    @course = Course.find(params[:course_id]) 
    @post = current_user.posts.build

  end

  # GET /posts/1/edit
  def edit
    # not_administrator
    @course = Course.find(params[:course_id]) 
  end

  # POST /posts
  # POST /posts.json
  def create
    not_administrator
    @post = current_user.posts.build(post_params) 
    @course = Course.find(params[:course_id]) 
    @user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to course_post_path(@course, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        flash[:danger] = "#{@user.first_name}, We have these errors: " + @post.errors.full_messages.to_sentence 
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    not_administrator
    # @post = current_user.posts.build(post_params) 
    @course = Course.find(params[:course_id]) 
    @user = current_user
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to course_post_path(@course, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        flash[:danger] = "#{@user.first_name}, We have these errors: " + @post.errors.full_messages.to_sentence 
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    not_administrator
    @course = Course.find(params[:course_id]) 
    @post.destroy
    respond_to do |format|
      
      format.html { flash[:danger] = 'Post was successfully destroyed.'
        redirect_to course_path(@course) }
      format.json { head :no_content }
    end
  end

  def import
    Post.import(params[:file])
    redirect_to posts_path, notice: 'Posts have been uploaded.'
  end  

  private

    def not_owner_of_post
      if current_user != @post.user
        flash[:danger] = "You need to be the author to perform this function!"
        redirect_back(fallback_location: root_path)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :course_id, :lecture_number, :section_number, :section_name )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= tinymce_assets %><%= tinymce %>
<%= form_for [@course, @course.posts.build] do |f| %>
<div class="form-inputs">
  <label for="">Section Name</label><br>
<%= f.select :section_name, (Post::RUBY_SECTIONS), class: "form-control" %>
  <br>
  <label for="">Lecture Number</label>
  <%= f.number_field :lecture_number, class: "form-control" %>
  <label for="">Video Title</label><br>
  <%= f.text_field :title, class: "form-control" %>
  <br>
  <%= f.text_area :body,  class: "tinymce", :rows => 20, :cols => 40 %>
  <%= f.number_field :course_id %>
</div>
<div class="form-actions">
  <%= f.button :submit, class: 'btn btn btn-outline-success' %>
</div>
<% end %>

app/views/posts/edit.html.erb
<%= tinymce_assets %><%= tinymce %>
<%= form_for([@course, @post]) do |f| %>
<div class="form-inputs">
  <label for="">Section Name</label><br>
  <%= f.select :section_name, (Post::RUBY_SECTIONS), class: "form-control" %>
  <br>
  <label for="">Lecture Number</label>
  <%= f.number_field :lecture_number, class: "form-control" %>
  <label for="">Video Title</label><br>
  <%= f.text_field :title, class: "form-control" %>
  <br>
  <%= f.text_area :body,  class: "tinymce", :rows => 20, :cols => 40 %>
  <%= f.number_field :course_id %>
</div>
<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover table-bordered"> 
  <thead>
    <tr>
      <th>Title</th>
      <th>Created At</th>
      <th>Body</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>about <%= time_ago_in_words(post.created_at) %> ago</td>
        <td><%= post.body %></td>
        <td><%= post.user.username %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.user == current_user %> 
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>




<div class="row">
  <div class="col-sm-3">
    <h4>Import Posts</h4>
    <%= form_tag import_posts_path, multipart: true do %>
    <%= file_field_tag :file, class: "btn btn-success btn-xs" %><br>
    <%= submit_tag "Upload Posts", class: "btn btn-info btn-xs" %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <h4>Export Posts</h4>
    <%= link_to "Download Posts", posts_path(format: :csv), 
      class: "btn btn-primary btn-xs round" %> 
  </div>
</div>


  

<div class="row">
  <div class="col-sm-3">
    <h4>Import Comments</h4>
    <%= form_tag import_comments_path, multipart: true do %>
    <%= file_field_tag :file, class: "btn btn-success btn-xs" %><br>
    <%= submit_tag "Upload Comments", class: "btn btn-info btn-xs" %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <h4>Export Comments</h4>
    <%= link_to "Download Comments", comments_path(format: :csv), 
      class: "btn btn-primary btn-xs round" %> 
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Video</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', course_path(@course) %>

app/views/posts/show.html.erb
<br>
<%= link_to 'Course Index', course_path(@course), class: 'btn btn-outline-secondary' %>
<p>
  <% if @post.user.image.present? %>
  <% image_tag @post.user.image_url(:thumb), class: 'rounded-circle' %>
  <% else %>
  <% image_tag 'no_image.png', class: 'rounded-circle' %>
  <% end %>
</p>
<div class="card text-center">
  <div class="card-header">
    <h3>
      <span class="badge badge-primary">
        <%= @post.title %>
      </span> 
    </h3>
    <br>
     <%= link_to 'Edit', edit_course_post_path(@course, @post), class: 'btn btn-outline-info pull-right' if current_user.try(:admin?) %>
  </div>
  <div class="card-block">
    <h4 class="card-title"><span class="badge badge-secondary"><%= @post.section_name %></span> 
    </h4>
    <p class="card-text"></p>
  </div>
</div>
<br>
<%= @post.body.html_safe %>
<%= render @post.comments.order(created_at: :desc ) %> 
<p>
  <% if current_user.try(:admin?) %> 
  <br>
<hr>
<strong>Add Comment:</strong>
<br>
<hr>
<%= render 'comments/form' %> 
</p>
<% link_to 'Edit', edit_course_post_comment_path(@course, @post.comments) if @post.user == current_user %> 
<% end %> 
<%= link_to 'Course Index', course_path(@course), class: 'btn btn-outline-secondary' %>
<br><br><br><br>